"""
Launch Working Adventure Works Dashboard with Real DAX Data
"""

import sys
import os
import json

# Add the parent directory to the path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dashboards.working_dashboard import WorkingDashboard

# Real DAX Results from Demo_1 semantic model (first 10 records for testing)
real_dax_results = {
    "success": True,
    "data": [
        {"adw_FactInternetSales[ProductKey]": "237", "adw_FactInternetSales[OrderDateKey]": "20161104", "adw_FactInternetSales[DueDateKey]": "20161116", "adw_FactInternetSales[ShipDateKey]": "20161111", "adw_FactInternetSales[CustomerKey]": "18642", "adw_FactInternetSales[PromotionKey]": "1", "adw_FactInternetSales[SalesTerritoryKey]": "6", "adw_FactInternetSales[SalesOrderNumber]": "SO96B76", "adw_FactInternetSales[SalesOrderLineNumber]": "5", "adw_FactInternetSales[RevisionNumber]": "1", "adw_FactInternetSales[OrderQuantity]": "1", "adw_FactInternetSales[UnitPrice]": 49.99, "adw_FactInternetSales[UnitPriceDiscountPct]": "0.0", "adw_FactInternetSales[DiscountAmount]": "0.0", "adw_FactInternetSales[ProductStandardCost]": 38.4923, "adw_FactInternetSales[TotalProductCost]": 38.4923, "adw_FactInternetSales[SalesAmount]": 49.99, "adw_FactInternetSales[TaxAmt]": 3.9992, "adw_FactInternetSales[Freight]": 1.2498, "adw_FactInternetSales[OrderDate]": "4/11/2016 12:00:00 am", "adw_FactInternetSales[DueDate]": "16/11/2016 12:00:00 am", "adw_FactInternetSales[ShipDate]": "11/11/2016 12:00:00 am", "adw_FactInternetSales[SalesID]": "103901", "adw_FactInternetSales[TotalLineAmount]": 55.239},
        {"adw_FactInternetSales[ProductKey]": "237", "adw_FactInternetSales[OrderDateKey]": "20161105", "adw_FactInternetSales[DueDateKey]": "20161117", "adw_FactInternetSales[ShipDateKey]": "20161112", "adw_FactInternetSales[CustomerKey]": "18642", "adw_FactInternetSales[PromotionKey]": "1", "adw_FactInternetSales[SalesTerritoryKey]": "6", "adw_FactInternetSales[SalesOrderNumber]": "SOAFE65", "adw_FactInternetSales[SalesOrderLineNumber]": "5", "adw_FactInternetSales[RevisionNumber]": "1", "adw_FactInternetSales[OrderQuantity]": "1", "adw_FactInternetSales[UnitPrice]": 49.99, "adw_FactInternetSales[UnitPriceDiscountPct]": "0.0", "adw_FactInternetSales[DiscountAmount]": "0.0", "adw_FactInternetSales[ProductStandardCost]": 38.4923, "adw_FactInternetSales[TotalProductCost]": 38.4923, "adw_FactInternetSales[SalesAmount]": 49.99, "adw_FactInternetSales[TaxAmt]": 3.9992, "adw_FactInternetSales[Freight]": 1.2498, "adw_FactInternetSales[OrderDate]": "5/11/2016 12:00:00 am", "adw_FactInternetSales[DueDate]": "17/11/2016 12:00:00 am", "adw_FactInternetSales[ShipDate]": "12/11/2016 12:00:00 am", "adw_FactInternetSales[SalesID]": "104007", "adw_FactInternetSales[TotalLineAmount]": 55.239},
        {"adw_FactInternetSales[ProductKey]": "310", "adw_FactInternetSales[OrderDateKey]": "20150509", "adw_FactInternetSales[DueDateKey]": "20150521", "adw_FactInternetSales[ShipDateKey]": "20150516", "adw_FactInternetSales[CustomerKey]": "12459", "adw_FactInternetSales[PromotionKey]": "1", "adw_FactInternetSales[SalesTerritoryKey]": "8", "adw_FactInternetSales[SalesOrderNumber]": "SO71832", "adw_FactInternetSales[SalesOrderLineNumber]": "1", "adw_FactInternetSales[RevisionNumber]": "1", "adw_FactInternetSales[OrderQuantity]": "2", "adw_FactInternetSales[UnitPrice]": 1434.86, "adw_FactInternetSales[UnitPriceDiscountPct]": "0.0", "adw_FactInternetSales[DiscountAmount]": "0.0", "adw_FactInternetSales[ProductStandardCost]": 747.2024, "adw_FactInternetSales[TotalProductCost]": 1494.4048, "adw_FactInternetSales[SalesAmount]": 2869.72, "adw_FactInternetSales[TaxAmt]": 229.5776, "adw_FactInternetSales[Freight]": 71.743, "adw_FactInternetSales[OrderDate]": "9/05/2015 12:00:00 am", "adw_FactInternetSales[DueDate]": "21/05/2015 12:00:00 am", "adw_FactInternetSales[ShipDate]": "16/05/2015 12:00:00 am", "adw_FactInternetSales[SalesID]": "118040", "adw_FactInternetSales[TotalLineAmount]": 3171.0406},
        {"adw_FactInternetSales[ProductKey]": "345", "adw_FactInternetSales[OrderDateKey]": "20150515", "adw_FactInternetSales[DueDateKey]": "20150527", "adw_FactInternetSales[ShipDateKey]": "20150522", "adw_FactInternetSales[CustomerKey]": "29485", "adw_FactInternetSales[PromotionKey]": "1", "adw_FactInternetSales[SalesTerritoryKey]": "1", "adw_FactInternetSales[SalesOrderNumber]": "SO71949", "adw_FactInternetSales[SalesOrderLineNumber]": "1", "adw_FactInternetSales[RevisionNumber]": "1", "adw_FactInternetSales[OrderQuantity]": "1", "adw_FactInternetSales[UnitPrice]": 2384.07, "adw_FactInternetSales[UnitPriceDiscountPct]": "0.0", "adw_FactInternetSales[DiscountAmount]": "0.0", "adw_FactInternetSales[ProductStandardCost]": 1912.1544, "adw_FactInternetSales[TotalProductCost]": 1912.1544, "adw_FactInternetSales[SalesAmount]": 2384.07, "adw_FactInternetSales[TaxAmt]": 190.7256, "adw_FactInternetSales[Freight]": 59.60175, "adw_FactInternetSales[OrderDate]": "15/05/2015 12:00:00 am", "adw_FactInternetSales[DueDate]": "27/05/2015 12:00:00 am", "adw_FactInternetSales[ShipDate]": "22/05/2015 12:00:00 am", "adw_FactInternetSales[SalesID]": "118479", "adw_FactInternetSales[TotalLineAmount]": 2634.39735},
        {"adw_FactInternetSales[ProductKey]": "529", "adw_FactInternetSales[OrderDateKey]": "20150604", "adw_FactInternetSales[DueDateKey]": "20150616", "adw_FactInternetSales[ShipDateKey]": "20150611", "adw_FactInternetSales[CustomerKey]": "29485", "adw_FactInternetSales[PromotionKey]": "1", "adw_FactInternetSales[SalesTerritoryKey]": "1", "adw_FactInternetSales[SalesOrderNumber]": "SO72296", "adw_FactInternetSales[SalesOrderLineNumber]": "1", "adw_FactInternetSales[RevisionNumber]": "1", "adw_FactInternetSales[OrderQuantity]": "1", "adw_FactInternetSales[UnitPrice]": 419.46, "adw_FactInternetSales[UnitPriceDiscountPct]": "0.0", "adw_FactInternetSales[DiscountAmount]": "0.0", "adw_FactInternetSales[ProductStandardCost]": 220.8576, "adw_FactInternetSales[TotalProductCost]": 220.8576, "adw_FactInternetSales[SalesAmount]": 419.46, "adw_FactInternetSales[TaxAmt]": 33.5568, "adw_FactInternetSales[Freight]": 10.4865, "adw_FactInternetSales[OrderDate]": "4/06/2015 12:00:00 am", "adw_FactInternetSales[DueDate]": "16/06/2015 12:00:00 am", "adw_FactInternetSales[ShipDate]": "11/06/2015 12:00:00 am", "adw_FactInternetSales[SalesID]": "120265", "adw_FactInternetSales[TotalLineAmount]": 463.5033},
        {"adw_FactInternetSales[ProductKey]": "214", "adw_FactInternetSales[OrderDateKey]": "20150620", "adw_FactInternetSales[DueDateKey]": "20150702", "adw_FactInternetSales[ShipDateKey]": "20150627", "adw_FactInternetSales[CustomerKey]": "29485", "adw_FactInternetSales[PromotionKey]": "1", "adw_FactInternetSales[SalesTerritoryKey]": "1", "adw_FactInternetSales[SalesOrderNumber]": "SO72562", "adw_FactInternetSales[SalesOrderLineNumber]": "1", "adw_FactInternetSales[RevisionNumber]": "1", "adw_FactInternetSales[OrderQuantity]": "3", "adw_FactInternetSales[UnitPrice]": 8.99, "adw_FactInternetSales[UnitPriceDiscountPct]": "0.0", "adw_FactInternetSales[DiscountAmount]": "0.0", "adw_FactInternetSales[ProductStandardCost]": 3.3963, "adw_FactInternetSales[TotalProductCost]": 10.1889, "adw_FactInternetSales[SalesAmount]": 26.97, "adw_FactInternetSales[TaxAmt]": 2.1576, "adw_FactInternetSales[Freight]": 0.6743, "adw_FactInternetSales[OrderDate]": "20/06/2015 12:00:00 am", "adw_FactInternetSales[DueDate]": "2/07/2015 12:00:00 am", "adw_FactInternetSales[ShipDate]": "27/06/2015 12:00:00 am", "adw_FactInternetSales[SalesID]": "121546", "adw_FactInternetSales[TotalLineAmount]": 29.8019},
        {"adw_FactInternetSales[ProductKey]": "477", "adw_FactInternetSales[OrderDateKey]": "20150712", "adw_FactInternetSales[DueDateKey]": "20150724", "adw_FactInternetSales[ShipDateKey]": "20150719", "adw_FactInternetSales[CustomerKey]": "29485", "adw_FactInternetSales[PromotionKey]": "1", "adw_FactInternetSales[SalesTerritoryKey]": "1", "adw_FactInternetSales[SalesOrderNumber]": "SO73124", "adw_FactInternetSales[SalesOrderLineNumber]": "1", "adw_FactInternetSales[RevisionNumber]": "1", "adw_FactInternetSales[OrderQuantity]": "1", "adw_FactInternetSales[UnitPrice]": 539.99, "adw_FactInternetSales[UnitPriceDiscountPct]": "0.0", "adw_FactInternetSales[DiscountAmount]": "0.0", "adw_FactInternetSales[ProductStandardCost]": 324.3855, "adw_FactInternetSales[TotalProductCost]": 324.3855, "adw_FactInternetSales[SalesAmount]": 539.99, "adw_FactInternetSales[TaxAmt]": 43.1992, "adw_FactInternetSales[Freight]": 13.4998, "adw_FactInternetSales[OrderDate]": "12/07/2015 12:00:00 am", "adw_FactInternetSales[DueDate]": "24/07/2015 12:00:00 am", "adw_FactInternetSales[ShipDate]": "19/07/2015 12:00:00 am", "adw_FactInternetSales[SalesID]": "123170", "adw_FactInternetSales[TotalLineAmount]": 596.689},
        {"adw_FactInternetSales[ProductKey]": "214", "adw_FactInternetSales[OrderDateKey]": "20150728", "adw_FactInternetSales[DueDateKey]": "20150809", "adw_FactInternetSales[ShipDateKey]": "20150804", "adw_FactInternetSales[CustomerKey]": "29485", "adw_FactInternetSales[PromotionKey]": "1", "adw_FactInternetSales[SalesTerritoryKey]": "1", "adw_FactInternetSales[SalesOrderNumber]": "SO73664", "adw_FactInternetSales[SalesOrderLineNumber]": "1", "adw_FactInternetSales[RevisionNumber]": "1", "adw_FactInternetSales[OrderQuantity]": "2", "adw_FactInternetSales[UnitPrice]": 8.99, "adw_FactInternetSales[UnitPriceDiscountPct]": "0.0", "adw_FactInternetSales[DiscountAmount]": "0.0", "adw_FactInternetSales[ProductStandardCost]": 3.3963, "adw_FactInternetSales[TotalProductCost]": 6.7926, "adw_FactInternetSales[SalesAmount]": 17.98, "adw_FactInternetSales[TaxAmt]": 1.4384, "adw_FactInternetSales[Freight]": 0.4495, "adw_FactInternetSales[OrderDate]": "28/07/2015 12:00:00 am", "adw_FactInternetSales[DueDate]": "9/08/2015 12:00:00 am", "adw_FactInternetSales[ShipDate]": "4/08/2015 12:00:00 am", "adw_FactInternetSales[SalesID]": "124315", "adw_FactInternetSales[TotalLineAmount]": 19.8679},
        {"adw_FactInternetSales[ProductKey]": "477", "adw_FactInternetSales[OrderDateKey]": "20150815", "adw_FactInternetSales[DueDateKey]": "20150827", "adw_FactInternetSales[ShipDateKey]": "20150822", "adw_FactInternetSales[CustomerKey]": "29485", "adw_FactInternetSales[PromotionKey]": "1", "adw_FactInternetSales[SalesTerritoryKey]": "1", "adw_FactInternetSales[SalesOrderNumber]": "SO74329", "adw_FactInternetSales[SalesOrderLineNumber]": "1", "adw_FactInternetSales[RevisionNumber]": "1", "adw_FactInternetSales[OrderQuantity]": "1", "adw_FactInternetSales[UnitPrice]": 539.99, "adw_FactInternetSales[UnitPriceDiscountPct]": "0.0", "adw_FactInternetSales[DiscountAmount]": "0.0", "adw_FactInternetSales[ProductStandardCost]": 324.3855, "adw_FactInternetSales[TotalProductCost]": 324.3855, "adw_FactInternetSales[SalesAmount]": 539.99, "adw_FactInternetSales[TaxAmt]": 43.1992, "adw_FactInternetSales[Freight]": 13.4998, "adw_FactInternetSales[OrderDate]": "15/08/2015 12:00:00 am", "adw_FactInternetSales[DueDate]": "27/08/2015 12:00:00 am", "adw_FactInternetSales[ShipDate]": "22/08/2015 12:00:00 am", "adw_FactInternetSales[SalesID]": "126104", "adw_FactInternetSales[TotalLineAmount]": 596.689},
        {"adw_FactInternetSales[ProductKey]": "214", "adw_FactInternetSales[OrderDateKey]": "20150831", "adw_FactInternetSales[DueDateKey]": "20150912", "adw_FactInternetSales[ShipDateKey]": "20150907", "adw_FactInternetSales[CustomerKey]": "29485", "adw_FactInternetSales[PromotionKey]": "1", "adw_FactInternetSales[SalesTerritoryKey]": "1", "adw_FactInternetSales[SalesOrderNumber]": "SO74849", "adw_FactInternetSales[SalesOrderLineNumber]": "1", "adw_FactInternetSales[RevisionNumber]": "1", "adw_FactInternetSales[OrderQuantity]": "4", "adw_FactInternetSales[UnitPrice]": 8.99, "adw_FactInternetSales[UnitPriceDiscountPct]": "0.0", "adw_FactInternetSales[DiscountAmount]": "0.0", "adw_FactInternetSales[ProductStandardCost]": 3.3963, "adw_FactInternetSales[TotalProductCost]": 13.5852, "adw_FactInternetSales[SalesAmount]": 35.96, "adw_FactInternetSales[TaxAmt]": 2.8768, "adw_FactInternetSales[Freight]": 0.899, "adw_FactInternetSales[OrderDate]": "31/08/2015 12:00:00 am", "adw_FactInternetSales[DueDate]": "12/09/2015 12:00:00 am", "adw_FactInternetSales[ShipDate]": "7/09/2015 12:00:00 am", "adw_FactInternetSales[SalesID]": "127004", "adw_FactInternetSales[TotalLineAmount]": 39.7358}
    ],
    "row_count": 50,
    "columns": ["adw_FactInternetSales[ProductKey]", "adw_FactInternetSales[OrderDateKey]", "adw_FactInternetSales[DueDateKey]", "adw_FactInternetSales[ShipDateKey]", "adw_FactInternetSales[CustomerKey]", "adw_FactInternetSales[PromotionKey]", "adw_FactInternetSales[SalesTerritoryKey]", "adw_FactInternetSales[SalesOrderNumber]", "adw_FactInternetSales[SalesOrderLineNumber]", "adw_FactInternetSales[RevisionNumber]", "adw_FactInternetSales[OrderQuantity]", "adw_FactInternetSales[UnitPrice]", "adw_FactInternetSales[UnitPriceDiscountPct]", "adw_FactInternetSales[DiscountAmount]", "adw_FactInternetSales[ProductStandardCost]", "adw_FactInternetSales[TotalProductCost]", "adw_FactInternetSales[SalesAmount]", "adw_FactInternetSales[TaxAmt]", "adw_FactInternetSales[Freight]", "adw_FactInternetSales[OrderDate]", "adw_FactInternetSales[DueDate]", "adw_FactInternetSales[ShipDate]", "adw_FactInternetSales[SalesID]", "adw_FactInternetSales[TotalLineAmount]"],
    "workspace": "CWYM Testing",
    "dataset": "demo_1"
}

if __name__ == "__main__":
    print("🚀 LAUNCHING WORKING ADVENTURE WORKS DASHBOARD")
    print("✅ Using Real DAX Data from Demo_1 Semantic Model")
    print("🔧 Robust Error Handling & Professional Design")
    print("=" * 60)
    
    # Create working dashboard with real DAX results
    dashboard = WorkingDashboard(real_dax_results)
    
    # Launch the working dashboard
    dashboard.run(port=8054)
